### ISSUE TITLE
Scipy Proceedings Lefthand Menu/Sidebar Update Needed

### ISSUE THREAD

**Issue by katyhuff** [scipy-conference/conference.scipy.org#15]
The sidebar on the site needs to be updated to include a link to "2015". That has to happen in the script (wherever the website is served) called proc_versions().  It is probably somewhere in a file like ./publisher/_static/proc_links.js ... which doesn't seem to be in this repo. Is it elsewhere in the server? (The state of the proper file in the proceedings repo seems to be irrelevant: https://github.com/scipy-conference/scipy_proceedings/blob/master/publisher/_static/proc_links.js)

Thoughts on this @aterrel @dpinte ?

**Comment by katyhuff** [comment]
Note that the sidebar I'm talking about is this one, which only goes up to 2015: 

![image](https://cloud.githubusercontent.com/assets/393899/9478197/348d1c88-4b2b-11e5-9266-5dcd8df2fee6.png)

**Comment by dpinte** [comment]
@katyhuff We need to ask that to the person who generated the static content with the proceedings. I only received the generated files.

**Comment by dpinte** [comment]
@katyhuff I edited the code directly on the server. The file does not seem to be under version control which is scary.

**Comment by katyhuff** [comment]
That is, indeed, quite scary.

**Comment by katyhuff** [comment]
Your change seems to have had the desired effect! Thanks @dpinte !

**Comment by stefanv** [comment]
IIRC, the idea is that the .js file always comes with the latest proceedings, and that there is a symlink on the server that gets updated to always point to that version.  E.g. (I don't know the URL exactly), /proceedings will point to /proceedings-2015, and then the .js will automatically load the correct version.  If this is not the way it works, we should make it work that way.

**Comment by dpinte** [comment]
This is from the js file:

```
function proc_versions() {
   var versions = ['2015', '2014', '2013', '2011', '2010', '2009', '2008'];
   var proc_url = 'http://conference.scipy.org/proceedings/scipy';
```
so, it's hardcoded at this point ... 

`/proceedings` points to an `index.html` page which lists the proceedings from each year.
