### ISSUE TITLE
Makefile uses someone's particular .ssh/config

### ISSUE THREAD

**Issue by deniederhut** [scipy-conference/conference.scipy.org#26]
The bug is that `make rsync` fails without properly resolving the hostname. The cause appears to be that the person who wrote the makefile was relying on a mapping between `conference` and the server name in their ssh configfile.

**Comment by dpinte** [comment]
@deniederhut yes, that was me ;-) Happy to change this.

**Comment by dpinte** [comment]
Fixed in #34

**Comment by dpinte** [comment]
Closed with #34
