### ISSUE TITLE
certificate expired, breaks DOI

### ISSUE THREAD

**Issue by jedbrown** [scipy-conference/conference.scipy.org#33]
The certificate expired October 28, and this is breaking DOI to conference proceedings. The proceedings appear to be served from elsewhere, but hopefully someone who can fix follows this repo. https://conference.scipy.org/proceedings/scipy2020/

If this repo is no longer active, perhaps the wiki can be updated. 
https://github.com/scipy/scipy/wiki/Web-service-infrastructure#conferencescipyorg

**Comment by dpinte** [comment]
The certificate will be updated shortly!

**Comment by dpinte** [comment]
The certificate has been updated.
