### ISSUE TITLE
Credential reset

### ISSUE THREAD

**Issue by jonathanrocher** [scipy-conference/conference.scipy.org#6]
When you request to receive an email with your credentials, the message is incomplete because it is missing the email address to write to if you don't get an email within a few minutes...
![screen shot 2014-03-07 at 10 41 51 am](https://f.cloud.github.com/assets/593945/2359439/b1076ea4-a617-11e3-9b94-f3ce5fe8e4f0.png)

**Comment by aterrel** [comment]
no longer valid as the site is no longer managed this way.
